### PR TITLE
Hook IsProcessorFeaturePresent to crash with STATUS_STACK_BUFFER_OVERRUN exception

### LINKED ISSUE #395: Capture __fastfail exceptions on windows
#258 

When software call __fastfail, the exception can't be caught 
https://github.com/googleprojectzero/winafl/blob/ea5f6b85572980bb2cf636910f622f36906940aa/winafl.c#L728
winafl wraps two functions in kernelbase.dll

for frida fuzzers, I think this can be done in a similar way as winafl,
but for sancov backend fuzzers, we would have to look at what libfuzzer is doing.

### PR DESCRIPTION
**Pull request by expend20**
Closes #395

I feel like I just created the architectual crutches by introducing [windows_hooks.rs](https://github.com/AFLplusplus/LibAFL/compare/main...expend20:LibAFL:fastfail-fix?expand=1#diff-039e662e2d4ee92b6b369a86ff38b2bf5e3a8a642e56a42386aff7c89f8efd31) with lazy_static in it. I basically needed the following, but didn't find a good way to do that. I appreciate the review comments
* I need a placeholder for keeping the result of `interceptor.replace` becase the function returns the original (not hooked) function so we could use it from our detour
* The reference for that placeholder can be passed as a parameter to the *_detour functions, now it is passed through a Mutex, but anyway the placeholder should live all the time hook exist

### CODE REVIEW

**Comment by domenukk** [comment]
Last I checked, static_init was the option with less overhead vs lazy_static, not sure if it's relevant https://crates.io/crates/static_init

File: libafl_frida/src/windows_hooks.rs [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+use lazy_static::lazy_static;
+use libafl::bolts::os::windows_exceptions::{handle_exception, EXCEPTION_POINTERS};
+
+type IsProcessorFeaturePresentFunc = unsafe extern "C" fn(feature: u32) -> bool;
+type UnhandledExceptionFilterFunc =
+    unsafe extern "C" fn(exceptioninfo: *mut EXCEPTION_POINTERS) -> i32;
+
+lazy_static! {
+    static ref GUM: Gum = unsafe { Gum::obtain() };
+    static ref IS_PROCESSOR_FEATURE_PRESENT: Mutex<UnsafeCell<Option<IsProcessorFeaturePresentFunc>>> =
```
[the remark this answers is not in the document]
Comment (domenukk) [reply libafl_frida/src/windows_hooks.rs:14]: Can't you use a static pointer that you assign to in initialize? It wouldn't be an issue if, worst case, it's done twice (but it'll be faster on access later)?

[the remark this answers is not in the document]
Comment (expend20) [reply libafl_frida/src/windows_hooks.rs:14]: > Are you sure you need a Mutex here?
you mean, you're fine with lazy static (or static_init) but not that fine with Mutex? In that case I can try to get rid of Mutex only

[the remark this answers is not in the document]
Comment (tokatoka) [reply libafl_frida/src/windows_hooks.rs:14]: I think we don't even need this function pointer
If what we essentially want is to call the original function, then you can directly call the windows api through windows-rs
https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Threading/fn.IsProcessorFeaturePresent.html

[the remark this answers is not in the document]
Comment (expend20) [reply libafl_frida/src/windows_hooks.rs:14]: > If what we essentially want is to call the original function

Interesting, I thought it would be the hooked one

[the remark this answers is not in the document]
Comment (expend20) [reply libafl_frida/src/windows_hooks.rs]: Ok. Got rid of mutex, another interesting behavior, if I put Gum::obtain() outside of the lazy_static -- frida crashes

**Comment by expend20** [comment]
> Last I checked, static_init was the option with less overhead vs lazy_static, not sure if it's relevant https://crates.io/crates/static_init

removed lazy_init fully, please have a final @domenukk @tokatoka

File: libafl/src/bolts/os/windows_exceptions.rs [hunk 2]
```diff
@@ -315,8 +318,12 @@ unsafe fn internal_handle_exception(
     }
 }
 
-/// Internal function that is being called whenever an exception arrives (stdcall).
-unsafe extern "system" fn handle_exception(exception_pointers: *mut EXCEPTION_POINTERS) -> c_long {
+/// Function that is being called whenever an exception arrives (stdcall).
+/// # Safety
+/// This function is unsafe because it is called by the OS
+pub unsafe extern "system" fn handle_exception(
```
Comment (expend20) [inline libafl/src/bolts/os/windows_exceptions.rs:324]: is it ok to be public? @tokatoka we could also minimize the damage by using `pub(crate)` I think

File: libafl/src/bolts/os/windows_exceptions.rs [hunk 3]
```diff
@@ -315,8 +318,12 @@ unsafe fn internal_handle_exception(
     }
 }
 
-/// Internal function that is being called whenever an exception arrives (stdcall).
-unsafe extern "system" fn handle_exception(exception_pointers: *mut EXCEPTION_POINTERS) -> c_long {
+/// Function that is being called whenever an exception arrives (stdcall).
+/// # Safety
+/// This function is unsafe because it is called by the OS
```
Comment (domenukk) [inline libafl/src/bolts/os/windows_exceptions.rs:323]: Maybe something like `Should never be called directly, only called by the OS` or something?

File: libafl_frida/src/windows_hooks.rs [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+pub fn initialize(gum: &Gum) {
+    let is_processor_feature_present =
+        Module::find_export_by_name(Some("kernel32.dll"), "IsProcessorFeaturePresent");
+    let is_processor_feature_present = is_processor_feature_present.unwrap();
+    if is_processor_feature_present.is_null() {
+        panic!("IsProcessorFeaturePresent not found");
+    }
+    let unhandled_exception_filter =
+        Module::find_export_by_name(Some("kernel32.dll"), "UnhandledExceptionFilter");
+    let unhandled_exception_filter = unhandled_exception_filter.unwrap();
```
Comment (tokatoka) [inline libafl_frida/src/windows_hooks.rs:17]: could you return Err(Error::Unknow("Some err msg")) in these locations instead of calling panic!() and unwrap()?

and then you can change the function signature to `pub fn initialize(gum: &Gum) -> Result<(), Error>`

File: libafl/src/bolts/os/windows_exceptions.rs (hunk 2 above)
Comment (tokatoka) [reply libafl/src/bolts/os/windows_exceptions.rs:324]: I think it's ok.

File: libafl_frida/src/windows_hooks.rs (hunk 4 above)
Comment (expend20) [reply libafl_frida/src/windows_hooks.rs:23]: Should be fixed now, but that `to_string()` looks a bit ugly to me, is that correct way of calling `Error()`?

File: libafl/src/bolts/os/windows_exceptions.rs (hunk 3 above)
Comment (expend20) [reply libafl/src/bolts/os/windows_exceptions.rs:323]: Any other better wording for this?

Comment (domenukk) [reply libafl/src/bolts/os/windows_exceptions.rs:323]: Just somehow indicate that's it's never safe if you call it manually (or is it?)

File: libafl_frida/src/executor.rs [hunk 5]
```diff
@@ -149,7 +149,7 @@ where
         }
 
         #[cfg(windows)]
-        initialize(&gum);
+        initialize(&gum).unwrap();
```
Comment (domenukk) [inline libafl_frida/src/executor.rs:152]: We shouldn't unwrap here either, but return a Result, unless if we are confident this cannot fail (which may be the case?)

File: libafl_frida/src/windows_hooks.rs (hunk 4 above)
Comment (domenukk) [reply libafl_frida/src/windows_hooks.rs:23]: Could this ever fail? Else a panic would be okay here.
As for the string, the exception owns the string, so that'd be the proper way

Comment (expend20) [reply libafl_frida/src/windows_hooks.rs:23]: I think it can't fail unless something is very wrong with the OS. Should I return panic then?

File: libafl_frida/src/executor.rs (hunk 5 above)
Comment (expend20) [reply libafl_frida/src/executor.rs:152]: okay, in case we've decided not to panic and we want handle the error by passing it on upper level, how could we do that in a constructor? The only value we can return is Self.

Comment (domenukk) [reply libafl_frida/src/executor.rs:152]: There are no constrictors in rust, it's a normal method returning `Self` right now. You'd change the method signature to return `Result<Self, Error>` instead ;)

Comment (expend20) [reply libafl_frida/src/executor.rs:152]: Thanks. I suspect you're not going to be happy if `FridaInProcessExecutor::new()` returns `Result<Self, Error>`, right?

Comment (domenukk) [reply libafl_frida/src/executor.rs:152]: I'd be very happy about it, if that's the right thing to do here :)
Basically only panic inside the library (and/or unwrap) if something will never fail. Finding functions in windows may be one such example, I'll leave that decision up to you

File: libafl/src/bolts/os/windows_exceptions.rs (hunk 3 above)
Comment (domenukk) [reply libafl/src/bolts/os/windows_exceptions.rs:323]: Is there any reason to call this for users? Else just weite it's not safe to call directly

File: libafl_frida/src/executor.rs (hunk 5 above)
Comment (expend20) [reply libafl_frida/src/executor.rs:152]: Okay think panic is more suitable here

File: libafl_frida/src/windows_hooks.rs (hunk 4 above)
Comment (expend20) [reply libafl_frida/src/windows_hooks.rs:17]: Switched to panic back, as discussed with @domenukk, is it ok for you @tokatoka ?

Comment (tokatoka) [reply libafl_frida/src/windows_hooks.rs:17]: sure

File: libafl/src/bolts/os/windows_exceptions.rs (hunk 3 above)
Comment (expend20) [reply libafl/src/bolts/os/windows_exceptions.rs:323]: We found at least one reason to call it from our code, that's in UnhandledExceptionFilter hook. If this case is not worh mentiong in comments, we can write `Should never be called directly, only called by the OS` -- would that be ok?
