### PR TITLE
Fix double crash for solutions with the same filename (#1232)

### LINKED ISSUE #1232: Double crash with `CachedOnDiskCorpus`
**Describe the bug**

[This commit](https://github.com/AFLplusplus/LibAFL/commit/b519d249817742cc64027bfbfd09c11350d879a3) introduced a bug, where clients crash after the target signaled with `SIGABRT`.

Corpus definition:

```rust
 CachedOnDiskCorpus::with_meta_format(
                    corpus_dir.clone(),
                    1000,
                    OnDiskMetadataFormat::Json,
                )
```

Randomly 1-2 clients crash with a "Double crash" when using `CachedOnDiskCorpus`.

```
2023-04-26T21:56:05.048703382+02:00	ERROR	Crashed with SIGABRT
2023-04-26T21:56:05.048720404+02:00	ERROR	Double crash

2023-04-26T21:56:05.048723671+02:00	ERROR	We crashed at addr 0x3e9000de825, but are not in the target... Bug in the fuzzer? Exiting.
2023-04-26T21:56:05.107669336+02:00	ERROR	━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ CRASH ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Received signal SIGABRT at 0x007fc6d1744a7c, fault address: 0x00000000000000
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ REGISTERS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
r8 : 0x007ffc170faca0, r9 : 0x00000000000002, r10: 0x00000000000008, r11: 0x00000000000246, 
r12: 0x00000000000006, r13: 0x00000000000016, r14: 0x0055cade3cc158, r15: 0x007ffc170faf50, 
rdi: 0x000000000de825, rsi: 0x000000000de825, rbp: 0x000000000de825, rbx: 0x007fc6d16ad240, 
rdx: 0x00000000000006, rax: 0x00000000000000, rcx: 0x007fc6d1744a7c, rsp: 0x007ffc170fabd0, 
rip: 0x007fc6d1744a7c, efl: 0x00000000000246, 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   0: libafl::bolts::minibsod::generate_minibsod
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/bolts/minibsod.rs:616:30
   1: libafl::executors::inprocess::unix_signal_handler::inproc_crash_handler
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/executors/inprocess.rs:815:25
   2: libafl::executors::inprocess::unix_signal_handler::<impl libafl::bolts::os::unix_signals::Handler for libafl::executors::inprocess::InProcessExecutorHandlerData>::handle
   3: libafl::bolts::os::unix_signals::handle_signal
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/bolts/os/unix_signals.rs:376:5
   4: <unknown>
   5: __pthread_kill_implementation
             at ./nptl/pthread_kill.c:43:17
      __pthread_kill_internal
             at ./nptl/pthread_kill.c:78:10
      __GI___pthread_kill
             at ./nptl/pthread_kill.c:89:10
   6: __GI_raise
             at ./signal/../sysdeps/posix/raise.c:26:13
   7: __GI_abort
             at ./stdlib/abort.c:79:7
   8: panic_abort::__rust_start_panic::abort
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/panic_abort/src/lib.rs:42:17

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ MAPS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
...

2023-04-26T21:56:05.107693825+02:00	ERROR	Type QUIT to restart the child
2023-04-26T21:56:15.275314059+02:00	ERROR	Crashed with SIGABRT
2023-04-26T21:56:15.275354003+02:00	ERROR	Child crashed!
2023-04-26T21:56:15.361376935+02:00	ERROR	input: "0.trace"
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ CRASH ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Received signal SIGABRT at 0x007fc6d1744a7c, fault address: 0x00000000000000
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ REGISTERS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
r8 : 0x007ffc170f5ac0, r9 : 0x00000000000000, r10: 0x00000000000008, r11: 0x00000000000246, 
r12: 0x00000000000006, r13: 0x00000000000016, r14: 0x00000000000001, r15: 0x00000000000001, 
rdi: 0x000000000de821, rsi: 0x000000000de821, rbp: 0x000000000de821, rbx: 0x007fc6d16ad240, 
rdx: 0x00000000000006, rax: 0x00000000000000, rcx: 0x007fc6d1744a7c, rsp: 0x007ffc170f59f0, 
rip: 0x007fc6d1744a7c, efl: 0x00000000000246, 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   0: libafl::bolts::minibsod::generate_minibsod
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/bolts/minibsod.rs:616:30
   1: libafl::executors::inprocess::unix_signal_handler::inproc_crash_handler
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/executors/inprocess.rs:783:21
   2: libafl::executors::inprocess::unix_signal_handler::<impl libafl::bolts::os::unix_signals::Handler for libafl::executors::inprocess::InProcessExecutorHandlerData>::handle
   3: libafl::bolts::os::unix_signals::handle_signal
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/bolts/os/unix_signals.rs:376:5
   4: <unknown>
   5: __pthread_kill_implementation
             at ./nptl/pthread_kill.c:43:17
      __pthread_kill_internal
             at ./nptl/pthread_kill.c:78:10
      __GI___pthread_kill
             at ./nptl/pthread_kill.c:89:10
   6: __GI_raise
             at ./signal/../sysdeps/posix/raise.c:26:13
   7: __GI_abort
             at ./stdlib/abort.c:79:7
   8: __libc_message
             at ./libio/../sysdeps/posix/libc_fatal.c:155:5
   9: malloc_printerr
             at ./malloc/malloc.c:5664:3
  10: _int_free
             at ./malloc/malloc.c:4439:5
  11: __GI___libc_free
             at ./malloc/malloc.c:3391:7
  12: wolfSSL_Free
             at target/x86_64-unknown-linux-gnu/release/build/wolfssl-sys-51acd48d2b19f9e7/out/wolfcrypt/src/memory.c:212:9
  13: AddSessionToCache
             at target/x86_64-unknown-linux-gnu/release/build/wolfssl-sys-51acd48d2b19f9e7/out/src/ssl.c:13557:9
  14: AddSession
             at target/x86_64-unknown-linux-gnu/release/build/wolfssl-sys-51acd48d2b19f9e7/out/src/ssl.c:13673:15
  15: DoSessionTicket
             at target/x86_64-unknown-linux-gnu/release/build/wolfssl-sys-51acd48d2b19f9e7/out/src/internal.c:26939:9
  16: DoHandShakeMsgType
             at target/x86_64-unknown-linux-gnu/release/build/wolfssl-sys-51acd48d2b19f9e7/out/src/internal.c:14286:15
  17: DoHandShakeMsg
             at target/x86_64-unknown-linux-gnu/release/build/wolfssl-sys-51acd48d2b19f9e7/out/src/internal.c:14521:15
  18: ProcessReplyEx
             at target/x86_64-unknown-linux-gnu/release/build/wolfssl-sys-51acd48d2b19f9e7/out/src/internal.c:17445:31
  19: ProcessReply
             at target/x86_64-unknown-linux-gnu/release/build/wolfssl-sys-51acd48d2b19f9e7/out/src/internal.c:16863:12
  20: wolfSSL_connect
             at target/x86_64-unknown-linux-gnu/release/build/wolfssl-sys-51acd48d2b19f9e7/out/src/ssl.c:11878:36
  21: wolfSSL_ex_wrapper
             at target/x86_64-unknown-linux-gnu/release/build/wolfssl-sys-51acd48d2b19f9e7/out/src/ssl.c:14197:19
  22: wolfSSL_accept_ex
             at target/x86_64-unknown-linux-gnu/release/build/wolfssl-sys-51acd48d2b19f9e7/out/src/ssl.c:14265:16
  23: wolfssl::ssl::SslStream<S>::do_handshake
             at crates/wolfssl/src/ssl.rs:748:13
      <tlspuffin::wolfssl::WolfSSL as puffin::put::Put<tlspuffin::protocol::TLSProtocolBehavior>>::progress
             at tlspuffin/src/wolfssl/mod.rs:200:43
  24: puffin::trace::TraceContext<PB>::next_state
             at puffin/src/trace.rs:222:9
      puffin::trace::InputAction<M>::input
             at puffin/src/trace.rs:603:9
      puffin::trace::Action<M>::execute
             at puffin/src/trace.rs:470:37
  25: puffin::trace::Trace<M>::execute
             at puffin/src/trace.rs:366:13
  26: puffin::fuzzer::harness::harness
             at puffin/src/fuzzer/harness.rs:43:23
      core::ops::function::FnMut::call_mut
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:166:5
  27: <libafl::executors::inprocess::GenericInProcessExecutor<H,HB,OT,S> as libafl::executors::Executor<EM,Z>>::run_target
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/executors/inprocess.rs:140:19
      <libafl::executors::timeout::TimeoutExecutor<E> as libafl::executors::Executor<EM,Z>>::run_target
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/executors/timeout.rs:353:23
      libafl::fuzzer::StdFuzzer<CS,F,OF,OT>::execute_input
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/fuzzer/mod.rs:630:25
  28: <libafl::fuzzer::StdFuzzer<CS,F,OF,OT> as libafl::fuzzer::EvaluatorObservers<OT>>::evaluate_input_with_observers
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/fuzzer/mod.rs:462:25
      <libafl::fuzzer::StdFuzzer<CS,F,OF,OT> as libafl::fuzzer::Evaluator<E,EM>>::evaluate_input_events
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/fuzzer/mod.rs:491:9
      libafl::fuzzer::Evaluator::evaluate_input
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/fuzzer/mod.rs:124:9
  29: libafl::stages::mutational::MutationalStage::perform_mutational
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/stages/mutational.rs:133:35
      <libafl::stages::mutational::StdMutationalStage<E,EM,I,M,Z> as libafl::stages::Stage<E,EM,Z>>::perform
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/stages/mutational.rs:213:19
      <(Head,Tail) as libafl::stages::StagesTuple<E,EM,<Head as libafl::state::UsesState>::State,Z>>::perform_all
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/stages/mod.rs:147:9
      <libafl::fuzzer::StdFuzzer<CS,F,OF,OT> as libafl::fuzzer::Fuzzer<E,EM,ST>>::fuzz_one
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/fuzzer/mod.rs:576:9
  30: libafl::fuzzer::Fuzzer::fuzz_loop
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/fuzzer/mod.rs:188:13
      puffin::fuzzer::libafl_setup::RunClientBuilder<H,C,R,SC,EM,F,OF,OT,CS,MT,I>::run_client
             at puffin/src/fuzzer/libafl_setup.rs:284:13
      puffin::fuzzer::libafl_setup::start::{{closure}}
             at puffin/src/fuzzer/libafl_setup.rs:486:9
  31: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:310:13
      libafl::bolts::launcher::Launcher<CF,MT,S,SP>::launch
             at /home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/b519d24/libafl/src/bolts/launcher.rs:196:32
      puffin::fuzzer::libafl_setup::start
             at puffin/src/fuzzer/libafl_setup.rs:520:13
  32: puffin::cli::main
             at puffin/src/cli.rs:223:27
  33: core::ops::function::FnOnce::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:121:18
  34: std::rt::lang_start::{{closure}}
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:166:18
  35: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:287:13
      std::panicking::try::do_call
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:148:20
  36: main
  37: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  38: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  39: _start

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ MAPS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
...
```

**To Reproduce**
1. Checkout tlspuffin
2. Execute with: `cargo run -p tlspuffin --target x86_64-unknown-linux-gnu --features "wolfssl530" --release -- --cores 0-7`

**Expected behavior**
Clients should continue executing.

### PR DESCRIPTION
**Pull request by tokatoka**

### CODE REVIEW

File: libafl/src/corpus/inmemory_ondisk.rs [hunk 1]
```diff
@@ -304,7 +305,13 @@ where
     fn save_testcase(&self, testcase: &mut Testcase<I>, idx: CorpusId) -> Result<(), Error> {
         let file_name_orig = testcase.filename_mut().take().unwrap_or_else(|| {
             // TODO walk entry metadata to ask for pieces of filename (e.g. :havoc in AFL)
-            testcase.input().as_ref().unwrap().generate_name(idx.0)
+            let mut hasher = ahash::RandomState::with_seeds(0, 0, 0, 0).build_hasher();
```
Comment (domenukk) [inline libafl/src/corpus/inmemory_ondisk.rs:308]: Why always create the hasher, even when it's not used inside the function? Seems wasteful and somewhat pointless?

Comment (tokatoka) [reply libafl/src/corpus/inmemory_ondisk.rs:308]: generate_name() should use it.

`generate_name(idx.0, &mut hasher)`

Comment (domenukk) [reply libafl/src/corpus/inmemory_ondisk.rs:308]: It doesn't always? Why not create it inside if you need it? Imho an ideal name shouldn't be random, but log the mutations etc.

Comment (domenukk) [reply libafl/src/corpus/inmemory_ondisk.rs:308]: Nautilus doesn't use it for example

Comment (tokatoka) [reply libafl/src/corpus/inmemory_ondisk.rs:308]: The purpose of putting hasher into the argument is to making it clear it is suggested to use hasher to make the testcase names random. 
https://github.com/AFLplusplus/LibAFL/issues/1232#issuecomment-1526153149

> Imho an ideal name shouldn't be random, but log the mutations etc.
Yup, like afl, but not all mutators log the mutation result

Comment (domenukk) [reply libafl/src/corpus/inmemory_ondisk.rs:308]: I don't think that's a good solution, just adding a comment should be better. No need to change the API imho.
That being said, we can also consider having one corpus folder for each core somehow

Comment (tokatoka) [reply libafl/src/corpus/inmemory_ondisk.rs:308]: hmm ok

> That being said, we can also consider having one corpus folder for each core somehow
in tlspuffin's case there were 25 testcases with the same name, while there were only 8 cores fuzzing.

I think the problem is https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/corpus/inmemory_ondisk.rs#L316
this counter. It's easy to have clashing names if you monotonously increase it.

How do you think about putting the current time in nano sec instead of a counter here?

Comment (domenukk) [reply libafl/src/corpus/inmemory_ondisk.rs]: that's something that tlspuffin should do
