### PR TITLE
Fix regex fixing generated bindings for QEMU

### LINKED ISSUE #2128: libafl_qemu fails to build in rust:1.77 Docker image
**IMPORTANT**
1. You have verified that the issue to be present in the current `main` branch

Yes
**Describe the bug**
The following Dockerfile fails
**To Reproduce**
```dockerifle
FROM rust:1.77
RUN apt-get update && \
    apt-get install -y gpg lsb-release wget software-properties-common && \
    echo "deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-17 main" > /etc/apt/sources.list.d/apt.llvm.org.list && \
    wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key |  tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc && \
    apt update && \
    apt-get install -y llvm-17-dev llvm-17-tools && \
    apt-get update && \
    apt-get install -y git clang-17 libclang-17-dev libglib2.0-dev libpixman-1-dev libslirp-dev ninja-build pkg-config python3-venv
RUN git clone https://github.com/AFLplusplus/LibAFL && \
    cd LibAFL/libafl_qemu && \
    git checkout 2f7c19e && \
    cargo build
```
```
docker build -t libafl_qemu .
```
**Expected behavior**
That works
**Screen output/Screenshots**
```
52.76 warning: libafl_qemu_sys@0.12.0: No emulation mode feature enabled or EMULATION_MODE env specified for libafl_qemu, supported: usermode, systemmmode - defaulting to usermode
52.76 warning: libafl_qemu_sys@0.12.0: No architecture feature enabled or CPU_TARGET env specified for libafl_qemu, supported: arm, aarch64, i386, x86_64 - defaulting to x86_64
52.76 warning: libafl_qemu_sys@0.12.0: Qemu not found, cloning with git (c9519ee8b6cb1ba54b7df1001f7f39f07218d514)...
54.95 warning: libafl_qemu@0.12.0: CROSS_CC is not set, default to cc (things can go wrong if the selected cpu target (x86_64) is not the host arch (x86_64))
55.46 error[E0308]: arguments to this function are incorrect
55.46     --> libafl_qemu/src/emu/mod.rs:1141:23
55.46      |
55.46 1141 |             let num = libafl_qemu_sys::libafl_add_edge_hook(gen, exec, data);
55.46      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
55.46      |
55.46 note: expected unsafe fn, found normal fn
55.46     --> libafl_qemu/src/emu/mod.rs:1141:61
55.46      |
55.46 1141 |             let num = libafl_qemu_sys::libafl_add_edge_hook(gen, exec, data);
55.46      |                                                             ^^^
55.46      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _) -> _>`
55.46                 found enum `std::option::Option<extern "C" fn(_, _, _) -> _>`
55.46 note: expected unsafe fn, found normal fn
55.46     --> libafl_qemu/src/emu/mod.rs:1141:66
55.46      |
55.46 1141 |             let num = libafl_qemu_sys::libafl_add_edge_hook(gen, exec, data);
55.46      |                                                                  ^^^^
55.46      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _)>`
55.46                 found enum `std::option::Option<extern "C" fn(_, _)>`
55.46 note: function defined here
55.46     --> /LibAFL/target/debug/build/libafl_qemu_sys-c915b0231f37eee6/out/bindings.rs:3:361633
55.46      |
55.46 3    | ... -> :: std :: os :: raw :: c_int ; } extern "C" { pub fn libafl_add_edge_hook (gen : :: std :: option :: Option < unsafe extern "C" fn...
55.46      |                                                             ^^^^^^^^^^^^^^^^^^^^
55.46
55.46 error[E0308]: arguments to this function are incorrect
55.46     --> libafl_qemu/src/emu/mod.rs:1159:23
55.46      |
55.46 1159 |             let num = libafl_qemu_sys::libafl_add_block_hook(gen, post_gen, exec, data);
55.46      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
55.46      |
55.46 note: expected unsafe fn, found normal fn
55.46     --> libafl_qemu/src/emu/mod.rs:1159:62
55.46      |
55.46 1159 |             let num = libafl_qemu_sys::libafl_add_block_hook(gen, post_gen, exec, data);
55.46      |                                                              ^^^
55.46      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _) -> _>`
55.46                 found enum `std::option::Option<extern "C" fn(_, _) -> _>`
55.46 note: expected unsafe fn, found normal fn
55.46     --> libafl_qemu/src/emu/mod.rs:1159:67
55.46      |
55.46 1159 |             let num = libafl_qemu_sys::libafl_add_block_hook(gen, post_gen, exec, data);
55.46      |                                                                   ^^^^^^^^
55.46      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _)>`
55.46                 found enum `std::option::Option<extern "C" fn(_, _, _)>`
55.46 note: expected unsafe fn, found normal fn
55.46     --> libafl_qemu/src/emu/mod.rs:1159:77
55.46      |
55.46 1159 |             let num = libafl_qemu_sys::libafl_add_block_hook(gen, post_gen, exec, data);
55.46      |                                                                             ^^^^
55.46      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _)>`
55.46                 found enum `std::option::Option<extern "C" fn(_, _)>`
55.46 note: function defined here
55.46     --> /LibAFL/target/debug/build/libafl_qemu_sys-c915b0231f37eee6/out/bindings.rs:3:362221
55.46      |
55.46 3    | ...arg2 : u64) -> usize >) -> bool ; } extern "C" { pub fn libafl_add_block_hook (gen : :: std :: option :: Option < unsafe extern "C" fn...
55.47      |                                                            ^^^^^^^^^^^^^^^^^^^^^
55.47
55.48 error[E0308]: arguments to this function are incorrect
55.48     --> libafl_qemu/src/emu/mod.rs:1202:23
55.48      |
55.48 1202 |             let num = libafl_qemu_sys::libafl_add_read_hook(
55.48      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
55.48      |
55.48 note: expected unsafe fn, found normal fn
55.48     --> libafl_qemu/src/emu/mod.rs:1203:22
55.48      |
55.48 1203 |                 gen, exec1, exec2, exec4, exec8, exec_n, data,
55.48      |                      ^^^^^
55.48      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _)>`
55.48                 found enum `std::option::Option<extern "C" fn(_, _, _)>`
55.48 note: expected unsafe fn, found normal fn
55.48     --> libafl_qemu/src/emu/mod.rs:1203:29
55.48      |
55.48 1203 |                 gen, exec1, exec2, exec4, exec8, exec_n, data,
55.48      |                             ^^^^^
55.48      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _)>`
55.48                 found enum `std::option::Option<extern "C" fn(_, _, _)>`
55.48 note: expected unsafe fn, found normal fn
55.48     --> libafl_qemu/src/emu/mod.rs:1203:36
55.48      |
55.48 1203 |                 gen, exec1, exec2, exec4, exec8, exec_n, data,
55.48      |                                    ^^^^^
55.48      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _)>`
55.48                 found enum `std::option::Option<extern "C" fn(_, _, _)>`
55.48 note: expected unsafe fn, found normal fn
55.48     --> libafl_qemu/src/emu/mod.rs:1203:43
55.48      |
55.48 1203 |                 gen, exec1, exec2, exec4, exec8, exec_n, data,
55.48      |                                           ^^^^^
55.48      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _)>`
55.48                 found enum `std::option::Option<extern "C" fn(_, _, _)>`
55.48 note: expected unsafe fn, found normal fn
55.48     --> libafl_qemu/src/emu/mod.rs:1203:50
55.48      |
55.48 1203 |                 gen, exec1, exec2, exec4, exec8, exec_n, data,
55.48      |                                                  ^^^^^^
55.48      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _, _)>`
55.48                 found enum `std::option::Option<extern "C" fn(_, _, _, _)>`
55.48 note: function defined here
55.48     --> /LibAFL/target/debug/build/libafl_qemu_sys-c915b0231f37eee6/out/bindings.rs:3:362918
55.48      |
55.48 3    | ... arg2 : u64) -> usize >) -> bool ; } extern "C" { pub fn libafl_add_read_hook (gen : :: std :: option :: Option < unsafe extern "C" fn...
55.48      |                                                             ^^^^^^^^^^^^^^^^^^^^
55.48
55.49 error[E0308]: arguments to this function are incorrect
55.49     --> libafl_qemu/src/emu/mod.rs:1236:23
55.49      |
55.49 1236 |             let num = libafl_qemu_sys::libafl_add_write_hook(
55.49      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
55.49      |
55.49 note: expected unsafe fn, found normal fn
55.49     --> libafl_qemu/src/emu/mod.rs:1237:22
55.49      |
55.49 1237 |                 gen, exec1, exec2, exec4, exec8, exec_n, data,
55.49      |                      ^^^^^
55.49      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _)>`
55.49                 found enum `std::option::Option<extern "C" fn(_, _, _)>`
55.49 note: expected unsafe fn, found normal fn
55.49     --> libafl_qemu/src/emu/mod.rs:1237:29
55.49      |
55.49 1237 |                 gen, exec1, exec2, exec4, exec8, exec_n, data,
55.49      |                             ^^^^^
55.49      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _)>`
55.49                 found enum `std::option::Option<extern "C" fn(_, _, _)>`
55.49 note: expected unsafe fn, found normal fn
55.49     --> libafl_qemu/src/emu/mod.rs:1237:36
55.49      |
55.49 1237 |                 gen, exec1, exec2, exec4, exec8, exec_n, data,
55.49      |                                    ^^^^^
55.49      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _)>`
55.49                 found enum `std::option::Option<extern "C" fn(_, _, _)>`
55.49 note: expected unsafe fn, found normal fn
55.49     --> libafl_qemu/src/emu/mod.rs:1237:43
55.49      |
55.49 1237 |                 gen, exec1, exec2, exec4, exec8, exec_n, data,
55.49      |                                           ^^^^^
55.49      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _)>`
55.49                 found enum `std::option::Option<extern "C" fn(_, _, _)>`
55.49 note: expected unsafe fn, found normal fn
55.49     --> libafl_qemu/src/emu/mod.rs:1237:50
55.49      |
55.49 1237 |                 gen, exec1, exec2, exec4, exec8, exec_n, data,
55.49      |                                                  ^^^^^^
55.49      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _, _)>`
55.49                 found enum `std::option::Option<extern "C" fn(_, _, _, _)>`
55.49 note: function defined here
55.49     --> /LibAFL/target/debug/build/libafl_qemu_sys-c915b0231f37eee6/out/bindings.rs:3:363679
55.49      |
55.49 3    | ...usize) > , data : u64) -> usize ; } extern "C" { pub fn libafl_add_write_hook (gen : :: std :: option :: Option < unsafe extern "C" fn...
55.49      |                                                            ^^^^^^^^^^^^^^^^^^^^^
55.49
55.50 error[E0308]: arguments to this function are incorrect
55.50     --> libafl_qemu/src/emu/mod.rs:1260:23
55.50      |
55.50 1260 |             let num = libafl_qemu_sys::libafl_add_cmp_hook(gen, exec1, exec2, exec4, exec8, data);
55.50      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
55.50      |
55.50 note: expected unsafe fn, found normal fn
55.50     --> libafl_qemu/src/emu/mod.rs:1260:60
55.50      |
55.50 1260 |             let num = libafl_qemu_sys::libafl_add_cmp_hook(gen, exec1, exec2, exec4, exec8, data);
55.50      |                                                            ^^^
55.50      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _) -> _>`
55.50                 found enum `std::option::Option<extern "C" fn(_, _, _) -> _>`
55.50 note: expected unsafe fn, found normal fn
55.50     --> libafl_qemu/src/emu/mod.rs:1260:65
55.50      |
55.50 1260 |             let num = libafl_qemu_sys::libafl_add_cmp_hook(gen, exec1, exec2, exec4, exec8, data);
55.50      |                                                                 ^^^^^
55.50      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _, _)>`
55.50                 found enum `std::option::Option<extern "C" fn(_, _, _, _)>`
55.50 note: expected unsafe fn, found normal fn
55.50     --> libafl_qemu/src/emu/mod.rs:1260:72
55.50      |
55.50 1260 |             let num = libafl_qemu_sys::libafl_add_cmp_hook(gen, exec1, exec2, exec4, exec8, data);
55.50      |                                                                        ^^^^^
55.50      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _, _)>`
55.50                 found enum `std::option::Option<extern "C" fn(_, _, _, _)>`
55.50 note: expected unsafe fn, found normal fn
55.50     --> libafl_qemu/src/emu/mod.rs:1260:79
55.50      |
55.50 1260 |             let num = libafl_qemu_sys::libafl_add_cmp_hook(gen, exec1, exec2, exec4, exec8, data);
55.50      |                                                                               ^^^^^
55.50      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _, _)>`
55.50                 found enum `std::option::Option<extern "C" fn(_, _, _, _)>`
55.50 note: expected unsafe fn, found normal fn
55.50     --> libafl_qemu/src/emu/mod.rs:1260:86
55.50      |
55.50 1260 |             let num = libafl_qemu_sys::libafl_add_cmp_hook(gen, exec1, exec2, exec4, exec8, data);
55.50      |                                                                                      ^^^^^
55.50      = note: expected enum `std::option::Option<unsafe extern "C" fn(_, _, _, _)>`
55.50                 found enum `std::option::Option<extern "C" fn(_, _, _, _)>`
55.50 note: function defined here
55.50     --> /LibAFL/target/debug/build/libafl_qemu_sys-c915b0231f37eee6/out/bindings.rs:3:364887
55.50      |
55.50 3    | ...: * mut TCGTemp , oi : MemOpIdx) ; } extern "C" { pub fn libafl_add_cmp_hook (gen : :: std :: option :: Option < unsafe extern "C" fn ...
55.50      |                                                             ^^^^^^^^^^^^^^^^^^^
55.50
55.53 For more information about this error, try `rustc --explain E0308`.
55.54 The following warnings were emitted during compilation:
55.54
55.54 warning: libafl_qemu@0.12.0: CROSS_CC is not set, default to cc (things can go wrong if the selected cpu target (x86_64) is not the host arch (x86_64))
55.54
55.54 error: could not compile `libafl_qemu` (lib) due to 5 previous errors
```
**Additional context**

### PR DESCRIPTION
**Pull request by rmalmain**
Fix #2128
Also, avoid writing 2 times bindings to filesystem.

### CODE REVIEW

File: libafl_qemu/libafl_qemu_build/src/bindings.rs [hunk 1]
```diff
@@ -155,7 +155,7 @@ pub fn generate(
         bindings
             .allowlist_type("CPUX86State")
             .allowlist_type("X86CPU")
-    } else if cpu_target == "arssssm" {
```
Comment (domenukk) [inline libafl_qemu/libafl_qemu_build/src/bindings.rs:158]: Great typo

File: libafl_qemu/libafl_qemu_sys/src/x86_64_stub_bindings.rs [hunk 2]
```diff
@@ -13703,7 +13702,7 @@ extern "C" {
 extern "C" {
     pub fn libafl_add_read_hook(
         gen: ::std::option::Option<
-            unsafe extern "C" fn(
+             extern "C" fn(
```
Comment (domenukk) [inline libafl_qemu/libafl_qemu_sys/src/x86_64_stub_bindings.rs:13705]: Shouldn't this be unsafe? The raw pointer will later be dereferenced (or is the later function marked unsafe?)

Comment (rmalmain) [reply libafl_qemu/libafl_qemu_sys/src/x86_64_stub_bindings.rs:13705]: Maybe, but then we need to keep the other similar function signatures consistent.
In any case, here it's a problem since we were transmuting a safe function pointer to an unsafe one, which is not a good idea IMHO.
I think the rationale behind making it safe is that we are using it through the Qemu struct, which is unsafe by nature. I'd say that as long as the signature of the function pointer is correct, it should not cause additional safety issues.

FYI it's used concretely [there](https://github.com/AFLplusplus/qemu-libafl-bridge/blob/9f3e2399ee9b106dfbb8c3afcdfdf30e235fc88f/libafl/hook.c#L456-L457).

Comment (domenukk) [reply libafl_qemu/libafl_qemu_sys/src/x86_64_stub_bindings.rs:13705]: IMHO a function that takes a `*mut` ptr and potentially dereferences that can never be safe. So I would argue the original function should already be unsafe (and then we don't transmute safe -> unsafe either)

Comment (domenukk) [reply libafl_qemu/libafl_qemu_sys/src/x86_64_stub_bindings.rs:13705]: Ah lol nevermind it's C :P It's all unsafe anyway

Comment (rmalmain) [reply libafl_qemu/libafl_qemu_sys/src/x86_64_stub_bindings.rs:13705]: Sounds reasonable, it's true safe rust allows the creation of any raw pointer. It's better to properly propagate the unsafeness even for an unsafe structure.

Comment (rmalmain) [reply libafl_qemu/libafl_qemu_sys/src/x86_64_stub_bindings.rs:13705]: The good point is that we can remove the ugly fix of the bindings.
