### PR TITLE
Other/User defined WIndows Exceptions

### LINKED ISSUE #360: Windows Missing exception code.
**IMPORTANT**
1. You have verified that the issue to be present in the current `main` branch
yes

**Describe the bug**
Reported by @expend20 
Some exception are not covered here https://github.com/AFLplusplus/LibAFL/blob/3d436b75196f3b065f6e40c65df94f36bfabf8f7/libafl/src/bolts/os/windows_exceptions.rs#L88
so they crash at this unwrap()
https://github.com/AFLplusplus/LibAFL/blob/3d436b75196f3b065f6e40c65df94f36bfabf8f7/libafl/src/bolts/os/windows_exceptions.rs#L324

One example is error code "0x4001000a" (DBG_PRINTEXCEPTION_WIDE_C)

### PR DESCRIPTION
**Pull request by tokatoka**
partially resolves #360 
this pr adds `Exception::Others` that takes care of unlisted exceptions.

### CODE REVIEW

**Comment by domenukk** [comment]
What's missing here?

**Comment by tokatoka** [comment]
nothing is missed, I just havn't run an example to see it actually runs before

**Comment by tokatoka** [comment]
Seems Good

File: libafl/src/executors/inprocess.rs [hunk 1]
```diff
@@ -817,7 +817,7 @@ mod windows_exception_handler {
     }
 
     pub unsafe fn inproc_crash_handler<E, EM, I, OC, OF, OT, S, Z>(
-        code: ExceptionCode,
+        _code: ExceptionCode,
```
Comment (domenukk) [inline libafl/src/executors/inprocess.rs:820]: Why pass this in at all?

File: libafl/src/bolts/os/windows_exceptions.rs [hunk 2]
```diff
@@ -150,6 +152,7 @@ pub static CRASH_EXCEPTIONS: &[ExceptionCode] = &[
     ExceptionCode::HeapCorruption,
     ExceptionCode::StackBufferOverrun,
     ExceptionCode::AssertionFailure,
+    ExceptionCode::Others,
```
Comment (domenukk) [inline libafl/src/bolts/os/windows_exceptions.rs:155]: Singular `Other`? It's only one exception at that time, right?

Comment (tokatoka) [reply libafl/src/bolts/os/windows_exceptions.rs:155]: yes I added #[num_enum(default)] to ExceptionCode::Others so that if the exception is not listed above (like random exceptions raised by User's code), that exception is catecorized as `Others`

Comment (domenukk) [reply libafl/src/bolts/os/windows_exceptions.rs:155]: No, I mean using singular here instead of plural, since it's a single exception being thrown

Comment (tokatoka) [reply libafl/src/bolts/os/windows_exceptions.rs:155]: ok. my english grammar's problem 😿
