### PR TITLE
fix the build

### LINKED ISSUE #3731: Redundant Borrowing and Double Mapping in MappedCrossoverInsertMutator::mutate
### Description

The `MappedCrossoverInsertMutator::mutate` function performs redundant operations when accessing and mapping the corpus input:

1. The testcase is borrowed twice using `get_from_all(id)?.borrow_mut()`.
2. The input is loaded and mapped twice:
   - First to compute `other_size`
   - Second to retrieve the mapped input for mutation
3. Additional unnecessary `unwrap()` checks increase branching complexity.

This results in:
- Redundant function calls
- Extra borrow operations
- Unnecessary memory allocations
- Reduced readability

### Expected Behavior

The mapped input and its size should be retrieved in a single borrow scope and used directly for mutation without re-loading or re-mapping.

### PR DESCRIPTION
**Pull request by Aditya30ag**
## Description

This PR refactors and simplifies the logic inside `MappedCrossoverInsertMutator` by restructuring how `mapped_other_input` and `other_size` are derived.

### Key Changes
- Compute `(mapped_other_input, other_size)` together within a single scoped block.
- Avoid reloading and remapping the input multiple times.
- Remove redundant checks and repeated borrowing of `other_testcase`.
- Use `as_ref().map_or(0, Vec::<u8>::len)` to safely compute the size without consuming the mapped input.
- Unwrap `mapped_other_input` only after validating size constraints.

### Benefits
- Reduces duplicated logic and unnecessary re-borrowing.
- Improves readability and control flow clarity.
- Provides a slight performance improvement by avoiding repeated corpus/input loading.
- Preserves existing mutation semantics.

No functional behavior has been altered; this change is strictly a structural and readability improvement.

Closes #3731

---

### Checklist
- [x] I have run `./scripts/precommit.sh` and addressed all comments

### CODE REVIEW

File: crates/libafl/src/mutators/mutations.rs [hunk 1]
```diff
@@ -1635,10 +1634,9 @@ where
         // No need to load the input again, it'll still be cached.
         let other_input = &mut other_testcase.input().as_ref().unwrap();
         let wrapped_mapped_other_input = (self.input_mapper)(other_input).map_to_option_bytes();
-        if wrapped_mapped_other_input.is_none() {
+        let Some(mapped_other_input) = wrapped_mapped_other_input else {
```
Comment (domenukk) [inline crates/libafl/src/mutators/mutations.rs:1637]: Honestly? This actually looks good, but it doesn't do what it says on the PR at all?

Comment (Aditya30ag) [reply crates/libafl/src/mutators/mutations.rs:1637]: The PR description currently refers to an older PR that I had closed earlier due to messy changes and failing builds.

After fixing the build issues, I created a new branch, but I forgot to update and push the correct code along with an updated description.

I’ll make sure to keep the PR description properly updated going forward.
