### PR TITLE
Match by Ref fix

### LINKED ISSUE #2104: match_by_ref should accept a &Reference
We don't actually consume the Reference. We should accept a &Reference instead, which avoids unnecessary clones down the line if the Cow is owned.

### PR DESCRIPTION
**Pull request by addisoncrump**
I could've just opened a PR I guess. Closes #2104.

### CODE REVIEW

**Comment by tokatoka** [comment]
👍

**Comment by addisoncrump** [comment]
We need `Named` for `Reference` so we can use named metadata.

File: fuzzers/forkserver_libafl_cc/src/main.rs [hunk 1]
```diff
@@ -185,7 +185,7 @@ pub fn main() {
     if let Some(dynamic_map_size) = executor.coverage_map_size() {
         executor
             .observers_mut()
-            .match_by_ref_mut(observer_ref)
+            .match_by_ref_mut(&observer_ref)
```
Comment (domenukk) [inline fuzzers/forkserver_libafl_cc/src/main.rs:188]: We could just name this `get`?

Comment (addisoncrump) [reply fuzzers/forkserver_libafl_cc/src/main.rs:188]: Yup lol

Comment (domenukk) [reply fuzzers/forkserver_libafl_cc/src/main.rs:188]: Assuming this will be the normal API to get referencable stuff, going forward

**Comment by addisoncrump** [comment]
I would defer the changeover from name to reference to #2068. That is a massive change.

File: fuzzers/forkserver_libafl_cc/src/main.rs [hunk 2]
```diff
@@ -183,10 +183,7 @@ pub fn main() {
         .unwrap();
 
     if let Some(dynamic_map_size) = executor.coverage_map_size() {
-        executor
-            .observers_mut()
-            .match_by_ref_mut(observer_ref)
-            .unwrap()
+        executor.observers_mut()[&observer_ref]
```
[the remark this answers is not in the document]
Comment (domenukk) [reply fuzzers/forkserver_libafl_cc/src/main.rs:186]: Definitely increases the WTF/line 🤣

File: libafl_sugar/Cargo.toml [hunk 3]
```diff
@@ -17,7 +17,7 @@ all-features = true
 
 [features]
 python = ["pyo3", "libafl_qemu/python", "pyo3-build-config"]
-default = []
+default = ["libafl/adaptive_serialization"]
```
Comment (addisoncrump) [inline libafl_sugar/Cargo.toml:20]: clippy flat out refused to pass if this wasn't enabled. I'm not sure how to get around this.

**Comment by addisoncrump** [comment]
Just some last fixes in some fuzzers now. I'll circle back to this in the morning :yawning_face:

**Comment by addisoncrump** [comment]
Okay, supposing the QEMU runnres pass, this is ready to go :chart_with_upwards_trend:

File: fuzzers/fuzzbench_forkserver_cmplog/src/main.rs [hunk 4]
```diff
@@ -355,6 +355,7 @@ fn fuzz(
         let cmpmap = unsafe { OwnedRefMut::from_shmem(&mut cmplog_shmem) };
 
         let cmplog_observer = AFLppCmpLogObserver::new("cmplog", cmpmap, true);
+        let cmplog_ref = cmplog_observer.type_ref();
```
Comment (domenukk) [inline fuzzers/fuzzbench_forkserver_cmplog/src/main.rs:358]: Why not `.reference`?

**Comment by domenukk** [comment]
Looks great

File: fuzzers/fuzzbench_forkserver_cmplog/src/main.rs (hunk 4 above)
Comment (addisoncrump) [reply fuzzers/fuzzbench_forkserver_cmplog/src/main.rs:358]: Yeah that's more in-line with what we're using now anyways. I'll do a mass find-replace and merge, then.
