### PR TITLE
Fix #3155

### LINKED ISSUE #3155: Mutator wrappers like StdScheduledMutator do not implement the post_exec function
**Describe the bug**
Mutator wrappers like StdScheduledMutator, MutationChecker do not implement the post_exec function of the Mutator trait.
For example:
```rust
impl<M, I, S> Mutator<I, S> for MutationChecker<M>
where
    I: Hash,
    M: Mutator<I, S>,
{
    fn mutate(&mut self, state: &mut S, input: &mut I) -> Result<MutationResult, Error> {
        let before = generic_hash_std(input);
        self.inner.mutate(state, input)?;
        if before == generic_hash_std(input) {
            Ok(MutationResult::Skipped)
        } else {
            Ok(MutationResult::Mutated)
        }
    }
}
```

**Expected behavior**
```rust
impl<M, I, S> Mutator<I, S> for MutationChecker<M>
where
    I: Hash,
    M: Mutator<I, S>,
{
    fn mutate(&mut self, state: &mut S, input: &mut I) -> Result<MutationResult, Error> {
        let before = generic_hash_std(input);
        self.inner.mutate(state, input)?;
        if before == generic_hash_std(input) {
            Ok(MutationResult::Skipped)
        } else {
            Ok(MutationResult::Mutated)
        }
    }

    fn post_exec(&mut self, state: &mut S, new_corpus_id: Option<CorpusId>) -> Result<(), Error> {
        self.inner.post_exec(state, new_corpus_id)
    }
}
```

### PR DESCRIPTION
**Pull request by tokatoka**

### CODE REVIEW

**Comment by domenukk** [comment]
Can you at least copy&paste the title of the original issue? No clue what this PR does ..

File: fuzzers/structure_aware/baby_fuzzer_custom_input/src/input.rs [hunk 1]
```diff
@@ -125,6 +126,10 @@ where
         };
         Ok(MutationResult::Mutated)
     }
+    #[inline]
+    fn post_exec(&mut self, _state: &mut S, _new_corpus_id: Option<CorpusId>) -> Result<(), Error> {
```
Comment (domenukk) [inline fuzzers/structure_aware/baby_fuzzer_custom_input/src/input.rs:130]: Why can't this be inside the trait?
